### ISSUE TITLE
license conflict

### ISSUE THREAD

**Issue by jmtd** [Erick194/DOOM-II-RPG-JAVA-EXTRACTOR#1]
Hi, your LICENSE file is a copy of the GPL 3, but you say this in README

> Remember you can not use this to be sold or make money with this.

This is in conflict with the terms of LICENSE. One or the other need to change.

I would encourage you to remove the lines from README and to keep the GPL, but if you insist on a non-commercial clause, consider using something like [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)

**Comment by jmtd** [comment]
I think this issue is present in every one of your extractors, but I am only filing it once.

**Comment by Erick194** [comment]
Thank you for your observation, I decided for the non-commercial license. Maybe in the future I will change my mind.

**Comment by jmtd** [comment]
OK thanks for clarifying; I can close this issue now.

(I did start porting this to POSIX, got it working on Linux, but I don't want to contribute to something that doesn't meet the [Debian Free Software Guidelines](https://en.wikipedia.org/wiki/Debian_Free_Software_Guidelines), so I'll leave this for now. In case you wonder, the issue with non-commercial is not wanting to sell it; it's just incompatible with being hosted or downloaded from  an ad-supported web site, or put on a compilation DVD or CD of software, and various other situations that could be considered "commercial" but are not profit-making. Good luck with your projects and best wishes!)
